### ISSUE TITLE
Master board component alternatives 

### ISSUE THREAD

**Issue by romiller872** [open-dynamic-robot-initiative/master-board#103]
Hello all,

my classmates and me are trying to order the master board from Beta Layout. Due to the ongoing supply chain issues, Beta Layout asked for alternatives for the following components:

1.	IC2
2.	R7
3.	U$1
4.	U$2
5.	U$5

Does anyone know what alternatives can be used to replace those components?

Thanks in advance!

Robin

**Comment by thomasfla** [comment]
Hi, 
sorry for long delay, most of those components (except R7) are chipsets and can not be replaced by others without major redesign of the board.

I hope the shortage soon end.
