### ISSUE TITLE
Avoid the use of "master" and "slave"

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/master-board#11]
The word usage "master" and "slave" is considered problematic and these days people use different terminologies.

Please update the terminology in the repo.

See similar issue in https://github.com/machines-in-motion/synchronizer/issues/2

**Comment by thomasfla** [comment]
I propose to close this issue, since the hardware is already made. 
We are following the SPI conventions here. 
Of course, no offensive intent was taken during the design of this card..
