### ISSUE TITLE
[SDK] Use rad and rad/s for motor.position and motor.velocity

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/master-board#12]
At this point the `motor.position` and `motor.velocity` returns the quantities as they are reported by the udriver boards. The udriver/ti boards use the units `position: [rotations]` and `velocity: [kilo rotations / minute]`.

I strongly vote we change the values stored and returned by the SDK to SI unites. That is `position: [rad]` and `velocity: [rad/s]`.

**Comment by thomasfla** [comment]
This is planned for the refactoring of the API. The only non SI value will be the accelerometer with g values instead of m/s2 since it ease the the gravity compensation that is estimated on-board in the IMU. What do you think?

**Comment by jviereck** [comment]
I have a strong opinion to have everything in SI units. Not every user of the sdk might be doing gravity compensation / use the setup for a robotics experiment. Therefore, I would like the used units to be "neutral" / not application specific. This boils down to using SI units.
