### ISSUE TITLE
macOS support for wired connection.

### ISSUE THREAD

**Issue by olivier-stasse** [open-dynamic-robot-initiative/master-board#129]
This issue is to report some investigation related to macOS support for wired connection.

PF_RAW does not exist on MacOS.
Starting from http://newosxbook.com/bonus/vol1ch16.html Listing 16-2,
socket should be create with PF_NDRV.

Then appropriate demux should be done when reading the socket.

A modification of Link_manager is proposed in PR #128.

Wireless could be done, but it is more involved.

**Comment by MaximilienNaveau** [comment]
#128 Is merged now, we should keep this issue open until the wireless is done.

**Comment by MaximilienNaveau** [comment]
Thanks for the work!
