### ISSUE TITLE
Error for wireless request "Set Frequency" (8B04) :

### ISSUE THREAD

**Issue by dvogureckiy99** [open-dynamic-robot-initiative/master-board#144]
When I run `sudo ./setup_wifi.sh wlp2s0` I have got error:
```
+ sudo ip link set down wlp2s0
+ sudo iwconfig wlp2s0 mode monitor
+ sudo ip link set up wlp2s0
+ sudo iwconfig wlp2s0 channel
Error for wireless request "Set Frequency" (8B04) :
    too few arguments.
```
```
  *-network
       description: Wireless interface
       product: Dual Band Wireless-AC 3165 Plus Bluetooth
```

**Comment by olivier-stasse** [comment]
Sorry for not replying sooner but this question may be related to:
 - the Linux distribubition on the computer
 - the kernel run on the computer
 - the network card driver.
 We would need more information to fix the problem.
 
 I partially answered if similar questions are asked.
 Closing the issue by lack of activity. 
 Feel free to reopen it if needed.
