### ISSUE TITLE
[SDK] Add motor.SetMaxCurrentReference(current)

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/master-board#15]
Add a way to specify in the sdk a clamping on the current. E.g.:

```
motor.SetMaxCurrentReference(max_current)
```

Behavior:
* if `max_current > 0`, turns on a clamping on the current specified by `motor.SetCurrentReference`
* if `max_current == 0`, turns of the current clamping
* if `max_current < 0`, throws an `ValueException` error.

**Comment by thomasfla** [comment]
The clamping is planned to be implemented on the uDriver. The protocol is already prepared for that. We just need to expose it in the sdk and to implement it in the uDriver.

**Comment by jviereck** [comment]
Having it on the udrive sounds safer. Let's do that




Get Outlook for Android







On Thu, Nov 21, 2019 at 11:23 AM +0100, "thomasfla" <notifications@github.com> wrote:












The clamping is planned to be implemented on the uDriver. The protocol is already prepared for that. We just need to expose it in the sdk and to implement it in the uDriver.
