### ISSUE TITLE
[SDK] Ability to run as non-root user

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/master-board#18]
Right now running the `example.cpp` requires root access on Linux. It would be great to have a way to run the demo without need for root permissions.

**Comment by nim65s** [comment]
For the C++ example:
```
sudo setcap cap_net_admin,cap_net_raw+ep master-board-example
./master-board-example eth0
```

For the python example, it is more tricky.
Setting `setcap` on the python interpreter would work, but it's not a great idea.

One solution would be to make a C++ daemon, and use Python with RPC to it instead of bindings.

**Comment by nim65s** [comment]
I'll try with a kernel module tomorrow :)

**Comment by thomasfla** [comment]
The setcap solution seems good and flexible enough. @AlexisPotier could you add this in the documentation ?
