### ISSUE TITLE
[SDK] Option to have no printf when running on realtime loop

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/master-board#19]
When running on a hard realtime thread, using `printf` can be problematic. At this point, the code is printing a message of ill-sized package length from

```
void MasterBoardInterface::callback(uint8_t src_mac[6], uint8_t *data, int len)
{
  if (len != sizeof(sensor_packet_t))
  {
    printf("received a %d long packet\n", len);
    return;
  }
```

For the hard realtime scenario, it would be good to have a way to log these incidents but not print them.

**Comment by thomasfla** [comment]
agree, this was for debug.. We can remove it

**Comment by paLeziart** [comment]
I created a pull request for this issue, see #20

**Comment by paLeziart** [comment]
The pull request has been merged. I think we can close the issue.
