### ISSUE TITLE
[FIRMWARE] Firmware incompatible with latest version of the esp-idf

### ISSUE THREAD

**Issue by thomasfla** [open-dynamic-robot-initiative/master-board#3]
A temporary solution is to use this commit of the esp-idf:
git checkout 8d1a9c07a0ff90acc3bad7143ce5154774ec1643
git submodule update --init --recursive

We need to adapt to the new HAL of the ESP32...

**Comment by thomasfla** [comment]
@maximekli and @AlexisPotier are working on this

**Comment by thomasfla** [comment]
pending #63 addresses this this issue

**Comment by jviereck** [comment]
As #63 got merged, is this still required? I tried to compile with the latest 4.1 release of esp-idf but it failed.

**Comment by thomasfla** [comment]
@maximekli did update the code for esp-idf v4 and above, but we measured a slightly degraded communication performances, so we decided to keep the v3 for now..

**Comment by thomasfla** [comment]
Closing this issue for now, as we won't fix before we prove new espidf performs as well as what we have now. (maybe v5?)
