### ISSUE TITLE
Typo: Connexion

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/master-board#31]
Noticed there is a typo in this PR: `connexion` -> `connection` due to #30 (the typo shows up a few times).

**Comment by paLeziart** [comment]
Sorry I forgot to check everywhere for this typo. I removed it from the warning messages when there is a timeout but not in the rest of the code. I will make a PR.

**Comment by paLeziart** [comment]
@jviereck I fixed the `printf("Shutting down connexion (%s)\n", if_name_.c_str());` message and a typo in a comment. Do you remember if there are more "connexion" elsewhere?
