### ISSUE TITLE
Velocity is not in SI

### ISSUE THREAD

**Issue by thomasfla** [open-dynamic-robot-initiative/master-board#38]
Velocity is not in SI, (1000. / 60.) should be replaced by (2. * M_PI * 1000. / 60.) to convert krpm to rad/s.
Change should also affect velocity velocity_ref and kd

**Comment by jviereck** [comment]
Agreed. We are using the `2 * pi * 1000 / 60.` conversion for the CAN based communication as well [1].

Sorry I got this wrong.

Working on a PR now.

[1]: https://github.com/open-dynamic-robot-initiative/blmc_drivers/blob/master/src/motor_board.cpp#L293
