### ISSUE TITLE
[SDK] Segfault upon destruction

### ISSUE THREAD

**Issue by MaximilienNaveau** [open-dynamic-robot-initiative/master-board#65]
We have a repeatable segfault using the master_board_sdk.
This is causing trouble on the use of the robot as it prevent the proper destruction of the managing class. So some logs are not available.

**Comment by thomasfla** [comment]
I think this is related to #37. The refactoring and pending update of the robot should fix this.
We need the new firmware and sdk to be tested. Would you want to test it @MaximilienNaveau ?
