### ISSUE TITLE
Issue connecting with wifi

### ISSUE THREAD

**Issue by Akshay-9416** [open-dynamic-robot-initiative/master-board#76]
Hello,
I am trying to run example codes using wifi.
I was able run example code a few times but now suddenly I am facing this issue below.
![image](https://user-images.githubusercontent.com/60077708/100613221-311c7380-333a-11eb-805d-1a53df27c628.png)
i ran the below prequisite commands also
sudo rfkill unblock wifi
sudo ./setup_wifi.sh wlp0s20f3 1  

can someone please let us know what causes this issue?

follow up to this,
can we control the motors directly using setpositionref(val) function?

**Comment by thomasfla** [comment]
Hello
Closing the loop over wifi is challenging especially if the joint controller is running on the PC side.
It is now possible to use the low level impedance control running at 10khz directly on the udrivers. To use this, you need to update the uDriver firmware to the latest version. Then you will be able to set Kp, Kd and reference position and velocity.
