### ISSUE TITLE
Installing the SDK

### ISSUE THREAD

**Issue by HanTop310** [open-dynamic-robot-initiative/master-board#80]
Hi there, I have a few questions:
1. How do I install the SDK.
2. Are there built in commands or is it through a GUI?
3. Is the SDK compatible with multiple motors (8 or 12 to be exact)?
4. Are there operating systems that don't work with the sdk?
Thanks in advance :D!

**Comment by thomasfla** [comment]
Hello, I'll try to answer to each questions below:

1- The installation of the SDK is documented here https://github.com/open-dynamic-robot-initiative/master-board/tree/master/sdk/master_board_sdk

2- The SDK is code based, you will need to write a program in C++ or in Python to read sensor data and send current commands to your motors. You can have a look at this examples:
https://github.com/open-dynamic-robot-initiative/master-board/tree/master/sdk/master_board_sdk/example

3- It is possible to control up to 12 motors with the protocol, but it could be extended to 16 motors, witch is the hardware limit.

4- The SDK has only been tested on linux system.


As an additional note, know that using directly the SDK library is the lowest level access to the motors. On top on this we developed a more user friendly library that centralise the access to all the motor and also includes actuator abstraction such as gear ratio, torque to current conversion etc.. and also provide calibration routines to find the zero position of the actuators.
you can find this library here: https://github.com/open-dynamic-robot-initiative/odri_control_interface

Also for this kind of general questions you can post and get some help here: https://odri.discourse.group/
 
Best,
Thomas.
