### ISSUE TITLE
Problems with the manufacturing files of Master board

### ISSUE THREAD

**Issue by YMCPALRobotics** [open-dynamic-robot-initiative/master-board#93]
Hello,

We want to manufacture Master boards in another manufacturer (that isn't Beta layout). We’ve analyzed the manufacturing files, and we found two problems:

- For the C4 to C9 capacitors and the R17 resistor, the BOM indicates that the package is 0603 (imperial size) and the "Component Placement File" indicates that it is 0402 (imperial size). What is the correct size for these components?

- The model of the U$3 component (HR911105A, Ethernet connector) doesn’t fit with the footprint. Could you regenerate the manufacturing files to change the footprint by the correct one?

Thanks!

Yaiza

**Comment by thomasfla** [comment]
fixed by #98
